name: CI


on:
push:
pull_request:


jobs:
toy-run:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up Java (Temurin 17)
uses: actions/setup-java@v4
with:
distribution: temurin
java-version: '17'


- name: Set up Miniconda
uses: conda-incubator/setup-miniconda@v3
with:
auto-activate-base: true
channels: conda-forge,bioconda,defaults


- name: Install Nextflow
run: |
curl -s https://get.nextflow.io | bash
sudo mv nextflow /usr/local/bin/nextflow
nextflow -version


- name: Create toy VCF (matches toy sumstats & phenotypes)
shell: bash
run: |
mkdir -p resources/toy
cat > resources/toy/genotypes.vcf <<'EOF'
##fileformat=VCFv4.2
##contig=<ID=1>
##contig=<ID=2>
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT id1 id2 id3
1 10100 rs1 G A . PASS . GT 0/1 0/0 1/1
1 13500 rs2 T C . PASS . GT 0/1 1/1 0/0
2 70500 rs3 A G . PASS . GT 0/0 0/1 1/1
EOF
conda install -y -c bioconda htslib bcftools
bgzip -f resources/toy/genotypes.vcf
tabix -f -p vcf resources/toy/genotypes.vcf.gz


- name: Run Nextflow toy pipeline (C+T only, conda profile)
env:
NXF_DEFAULT_DSL: 2
run: |
nextflow run main.nf -profile conda \
--sumstats resources/toy/sumstats.tsv \
--vcf resources/toy/genotypes.vcf.gz \
--pheno resources/toy/phenotypes.tsv \
--methods ct \
--outdir outputs/ci


outputs/ci/scores/scores.tsv
